# Generated by Django 5.1.3 on 2024-11-10 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeldetalleventa',
            name='venta',
        ),
        migrations.AddField(
            model_name='modeldetalleventa',
            name='comprador',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_producto', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelventas',
            name='detalles_venta',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='app.modeldetalleventa'),
            preserve_default=False,
        ),
    ]
