# Generated by Django 5.1.3 on 2024-11-10 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_modeldetalleventa_venta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='modeldetalleventa',
            name='recibo_ventas',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
