# Generated by Django 5.1.3 on 2024-11-11 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_modeldetalleventa_recibo_ventas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modeldetalleventa',
            name='precio_unitario',
        ),
        migrations.RemoveField(
            model_name='modeldetalleventa',
            name='recibo_ventas',
        ),
        migrations.RemoveField(
            model_name='modelventas',
            name='detalles_venta',
        ),
        migrations.AddField(
            model_name='modelventas',
            name='productos_vendidos',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
